DROP TABLE pictures
IF EXISTS;

DROP SEQUENCE PICT_SEQ
IF EXISTS;


CREATE SEQUENCE PICT_SEQ
  AS INTEGER
START WITH 1;


/*@Column(name = "url")
    @JsonProperty("url")
    private String url;

    @Column(name = "loadpath")
    @JsonIgnore
    private String loadpath;


    @Column(name = "countLike")
    @JsonProperty("countLike")
    private int countLike;*/

CREATE TABLE pictures
(
  id     INTEGER GENERATED BY DEFAULT AS SEQUENCE PICT_SEQ PRIMARY KEY,
  url    VARCHAR(255),
  loadpath    VARCHAR(255),
  countLike    INTEGER
);
